name: namer_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  go_router: ^14.6.2
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3 # for dependency injection
  dio: ^5.8.0+1
  shared_preferences: ^2.2.3
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_ui_auth: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
